"editorconfig":
  - ".editorconfig"

"document":
  - "**/*.md"
  - "**/*.txt"
  - "**/*.rst"

"terraform":
  - ".github/actions/terraform**/action.yml"
  - ".github/workflows/terraform**.yml"

"textlint":
  - "**/.textlint*"

"yamllint":
  - "**/.yamllint"

"markdownlint":
  - "**/.markdownlint*.json"

"asdf":
  - "**/.tool-versions"

"actionlint":
  - ".github/workflows/actionlint.yml"
