---
name: Terraform Apply

description: Terraform Apply

inputs:
  GITHUB_APPS_TOKEN:
    description: GitHub App トークン
    required: true
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ inputs.working-directory }}
      env:
        TF_VAR_github_token: ${{ inputs.GITHUB_APPS_TOKEN }}
      shell: bash
