---
name: Terraform Apply

description: Terraform Apply

inputs:
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true
  TF_VAR_github_token:
    description: GitHub token
    required: true
  GITHUB_TOKEN:
    description: Terraform 実行時に利用する GitHub トークン
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        TF_VAR_github_token: ${{ inputs.TF_VAR_github_token }}
      shell: bash
