---
name: Terraform Plan

description: Terraform Plan

inputs:
  GITHUB_TOKEN:
    description: サードパーティの Action を実行するための権限を付与するための認証用トークン
    required: true
  GITHUB_APPS_TOKEN:
    description: GitHub App トークン
    required: true
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: ./.github/actions/setup-terraform
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Terraform Validate
      uses: ./.github/actions/terraform-validate
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Setup tfcmt
      uses: itkq/actions-tfcmt/setup@main

    - name: Terraform Plan
      id: terraform-plan
      run: |
        TARGET=$(echo ${{ inputs.working-directory }} | sed -e 's|^.*terraform/src/||' | cut -c 1-36)
        tfcmt --var target:$TARGET plan -patch -- terraform plan -no-color
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        TF_VAR_github_token: ${{ inputs.GITHUB_APPS_TOKEN }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Terraform Plan (failure) -> Status
      if: steps.terraform-plan.outcome == 'failure'
      run: exit 1
      shell: bash
