name: Generate PR Title and Description

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read # uses: actions/checkout
      pull-requests: write # uses: tqer39/generate-pr-description
    # Check if the PR is not created by 'renovate' or 'tqer39-apps'
    if: contains(fromJSON('["renovate[bot]", "tqer39-apps[bot]"]'), github.event.pull_request.user.login) == false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: tqer39/generate-pr-description@f04a03f058ece4ef29359f8da361f127b02fa25e # v2.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.OPENROUTER_API_KEY }}
          model: 'openai/gpt-4o-mini'
          locale: 'ja'
