---
name: Labeler

on:
  pull_request:

jobs:
  auto-labeling:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: actions/labeler@v5
