---
name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set PCT_TFPATH environment variable
        run: echo "PCT_TFPATH=$(which terraform)" >> $GITHUB_ENV

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: -a --show-diff-on-failure
