name: Set Common Secrets

on:
  workflow_dispatch:

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Set secrets in repositories
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          GHA_APP_ID: ${{ secrets.GHA_APP_ID }}
          GHA_APP_PRIVATE_KEY: ${{ secrets.GHA_APP_PRIVATE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ./scripts/set-common-github-secrets.sh ${{ github.repository_owner }}
