name: Set Common Secrets

on:
  workflow_dispatch:

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get repository list
        id: repo-list
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          repos=$(gh repo list ${{ github.repository_owner }} --json name -q '.[].name')
          echo "repos=$repos" >> $GITHUB_ENV

      - name: Set secrets in repositories
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          GHA_APP_ID: ${{ secrets.GHA_APP_ID }}
          GHA_APP_PRIVATE_KEY: ${{ secrets.GHA_APP_PRIVATE_KEY }}
        run: |
          for repo in ${{ steps.repo-list.outputs.repos }}; do
            echo "Setting secret for $repo"

            gh api -X PUT \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              /repos/${{ github.repository_owner }}/$repo/actions/secrets/GHA_APP_ID \
              -f encrypted_value=$GHA_APP_ID \
              -f key_id=$(gh api /repos/${{ github.repository_owner }}/$repo/actions/secrets/public-key | jq -r .key_id)

            gh api -X PUT \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              /repos/${{ github.repository_owner }}/$repo/actions/secrets/GHA_APP_PRIVATE_KEY \
              -f encrypted_value=$GHA_APP_PRIVATE_KEY \
              -f key_id=$(gh api /repos/${{ github.repository_owner }}/$repo/actions/secrets/public-key | jq -r .key_id)

          done
