name: Set Common Secrets

on:
  workflow_dispatch:

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set secrets in repositories
        env:
          GH_TOKEN: ${{ secrets.PAT_SET_COMMON_GITHUB_SECRETS }}
          GHA_APP_ID: ${{ secrets.GHA_APP_ID }}
          GHA_APP_PRIVATE_KEY: ${{ secrets.GHA_APP_PRIVATE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          repos=$(gh repo list "${{ github.repository_owner }}" --json name -q '.[].name')
          echo "owner: ${{ github.repository_owner }}"

          # Set secrets in repositories
          for repo in $repos; do
            echo ""
            echo "Setting secret for $repo"

            gh secret set GHA_APP_ID --repo "${{ github.repository_owner }}/$repo" --body "$GHA_APP_ID"
            gh secret set GHA_APP_PRIVATE_KEY --repo "${{ github.repository_owner }}/$repo" --body "$GHA_APP_PRIVATE_KEY"
            gh secret set OPENAI_API_KEY --repo "${{ github.repository_owner }}/$repo" --body "$OPENAI_API_KEY"
          done
