name: Set Common Secrets

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set secrets in repositories
        env:
          GH_TOKEN: ${{ secrets.PAT_SET_COMMON_GITHUB_SECRETS }}
          GHA_APP_ID: ${{ secrets.GHA_APP_ID }}
          GHA_APP_PRIVATE_KEY: ${{ secrets.GHA_APP_PRIVATE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ./scripts/set-common-github-secrets.sh ${{ github.repository_owner }}
