name: Set Common Secrets

on:
  workflow_dispatch:

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read repository list
        id: repo-list
        run: |
          repos=$(cat repositories.list)
          echo "repos=$repos" >> $GITHUB_ENV

      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Set secrets in repositories
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          secret_name="YOUR_SECRET_NAME"
          secret_value="YOUR_SECRET_VALUE"
          for repo in ${{ steps.repo-list.outputs.repos }}; do
            echo "Setting secret for $repo"
            gh api -X PUT \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              /repos/$repo/actions/secrets/$secret_name \
              -f encrypted_value=$secret_value \
              -f key_id=$(gh api /repos/$repo/actions/secrets/public-key | jq -r .key_id)
          done
